### ISSUE TITLE
Allow batch uploads for files

### ISSUE THREAD

**Issue by LanceLake** [nrl-ai/pautobot#22]
Right now, I can only upload one file at a time.. To be more technical, I can set up a batch upload, but I have to select each file. What would be helpful is to recurse through directories and perhaps select multiple files in the upload file window. That would allow me to select a batch of files to be uploaded and leave it running overnight to digest them all.

**Comment by vietanhdev** [comment]
Working on it. :D

**Comment by vietanhdev** [comment]
@LanceLake Implemented in v0.0.27. Please check.

**Comment by LanceLake** [comment]
This broke it. 

https://i.imgur.com/IMA0kjF.png

**Comment by LanceLake** [comment]
@vietanhdev just a suggestion, don't ask someone to test something, then close it before they can report back.

**Comment by vietanhdev** [comment]
@LanceLake Sorry. I just wanted to mark it done.
